version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: basic
    ports:
    - 5000:5000
    volumes:
      # - /mnt/nas/Musique/dl:/app/output
      - ./dockerOutput:/app/output